name: 'Setup environment'
description: 'Setup test environment'
runs:
  using: composite
  steps:
    - name: Setup MongoDb
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '4' # using mongo:4 for compatibility with almost all drivers

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.5' # node v18 is the highest supported version of all driver v4,v5,v6

    - name: Install dependencies
      shell: bash
      run: npm install
      working-directory: ./
