name: 'Setup environment'
description: 'Setup test environment'
runs:
  using: composite
  steps:
    - name: Setup Docker # using mongo:4 for the most compatible with drivers
      shell: bash
      run: |
        docker ps -aq | xargs -r docker stop
        docker container prune -f
        docker system prune -f
        docker run --name test__mongo -p 27017:27017 -d mongo:4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.5' # driver 4,5,6 all support node 18

    - name: Install dependencies
      shell: bash
      run: npm install
      working-directory: ./
